version: '3.8'

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/code
        ports:
            - 8000:8000
        depends_on: 
            - db
        environment:
            - "DJANGO_SECRET_KEY=duu4c9f#*8trb2z3djtkj020xj!$$89n&f5u6snsp1kwy&y04a+"
            - "DJANGO_DEBUG=True"
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes: 
    postgres_data:
